### ISSUE TITLE
dmg download issue

### ISSUE THREAD

**Issue by austinhutchison** [matiasbenedetto/squoosh-desktop-app#1]
Hi there - I was very impressed with the web app and wanted to download the desktop version. Unfortunately I didn't know how to use git lfs, I think this repo could be improved with the instructions to do so. 

Once I did figure out git lfs, I got the following error message
```
git lfs fetch --all
fetch: 1 object(s) found, done.                                                 
fetch: Fetching all references...
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/matiasbenedetto/squoosh-desktop-app.git/info/lfs'
```

So as far as I can tell there is no way to get the mac dmg file - and I'm not sure how to build :(

**Comment by AMDark** [comment]
I am also interested in the MacOS app. It crashes when downloading. Would anyone know how to solve it?

**Comment by uhlhosting** [comment]
DMG link is broken!

**Comment by matiasbenedetto** [comment]
I'm closing this because the `.dmg` download is working now: https://squoosh-desktop.vercel.app/
Thanks for reporting!

**Comment by uhlhosting** [comment]
Was this also updated to latest release?
