### ISSUE TITLE
dmg download issue

### ISSUE THREAD

**Issue by cokice** [matiasbenedetto/squoosh-desktop-app#3]
Cannot use dmg

**Comment by joedag32** [comment]
same here :( Hoping to use this on my Mac!

**Comment by antoinelbch** [comment]
+1

**Comment by rquirola** [comment]
+1

**Comment by srhinow** [comment]
+1

show this as normal text:

```
version https://git-lfs.github.com/spec/v1
oid sha256:a38ffaeb6e7e3cc8c41eadc1690d705b26398839f3a0ab926a1472aa8e7fbb43
size 66044612
```

**Comment by GerhardMes** [comment]
+1 
same here

**Comment by josepgarcia** [comment]
+1

**Comment by guxianbang** [comment]
+1

**Comment by IS-Martin** [comment]
+1

**Comment by jjmomo** [comment]
https://raw.githubusercontent.com/matiasbenedetto/squoosh-desktop-app/master/bin/mac/Squoosh%20Desktop-1.0.0.dmg
SHOW info:
version https://git-lfs.github.com/spec/v1
oid sha256:a38ffaeb6e7e3cc8c41eadc1690d705b26398839f3a0ab926a1472aa8e7fbb43
size 66044612

**Comment by stvhanna** [comment]
@matiasbenedetto Thanks for a great app, the dmg build is broken, any plans to fix it?

**Comment by matiasbenedetto** [comment]
I'm closing this because the `.dmg` download is working now: https://squoosh-desktop.vercel.app/
